// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olyywxcrzzwjruidqmli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seXl3eGNyenp3anJ1aWRxbWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzgxMzcsImV4cCI6MjA2OTcxNDEzN30.W84ziIoz4veUC_616EY0s2uFRtFWNiajP8Gf7cTYgXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});